// Viết chương trình có tên tiemSince, thông báo người dùng offline x phút....
// ví dụ : bạn đang chat với a, sau đó bạn a offline
// YÊU CẦU: update hiển thị thời gian offline trước 'x giây trước ' 'x phút trước','x ngày trước''x tháng trước''x năm trước'
